import { FatigueScore, MeetingStats } from '../types';

interface FatigueScoreCardProps {
  fatigueScore: FatigueScore;
  stats: MeetingStats;
}

const gradeSolidColors = {
  A: 'text-green-600',
  B: 'text-blue-600',
  C: 'text-yellow-600',
  D: 'text-orange-600',
  F: 'text-red-600',
};

function FatigueScoreCard({ fatigueScore, stats }: FatigueScoreCardProps) {
  const avgWeeklyHours = ((stats.totalHours / 30) * 7).toFixed(1);
  const colorClass = gradeSolidColors[fatigueScore.grade];

  return (
    <div className="bg-white rounded-2xl shadow-2xl p-8 max-w-2xl mx-auto border-4 border-gray-200" id="report-card">
      <div className="text-center mb-6">
        <h2 className="text-3xl font-bold mb-2">Meeting Fatigue Report Card</h2>
        <p className="text-gray-600">Last 30 Days Analysis</p>
      </div>

      {/* Score Circle */}
      <div className="flex justify-center mb-8">
        <div className="relative">
          <svg className="w-48 h-48 transform -rotate-90">
            <circle
              cx="96"
              cy="96"
              r="88"
              stroke="#e5e7eb"
              strokeWidth="12"
              fill="none"
            />
            <circle
              cx="96"
              cy="96"
              r="88"
              stroke="currentColor"
              strokeWidth="12"
              fill="none"
              strokeDasharray={`${(fatigueScore.score / 100) * 553} 553`}
              strokeLinecap="round"
              className={colorClass}
            />
          </svg>
          <div className="absolute inset-0 flex flex-col items-center justify-center">
            <div className={`text-6xl font-bold ${colorClass}`}>
              {fatigueScore.score}
            </div>
            <div className="text-2xl font-semibold text-gray-700">{fatigueScore.grade}</div>
          </div>
        </div>
      </div>

      {/* Badge */}
      <div className="text-center mb-6">
        <div className="inline-block bg-blue-50 rounded-full px-6 py-3 border-2 border-blue-200">
          <p className="text-lg font-semibold text-gray-800">{fatigueScore.badge}</p>
        </div>
      </div>

      {/* Quick Stats */}
      <div className="grid grid-cols-3 gap-4 mb-6">
        <div className="text-center p-3 bg-gray-50 rounded-lg">
          <div className="text-2xl font-bold text-blue-600">{stats.totalMeetings}</div>
          <div className="text-xs text-gray-600">Meetings</div>
        </div>
        <div className="text-center p-3 bg-gray-50 rounded-lg">
          <div className="text-2xl font-bold text-purple-600">{avgWeeklyHours}h</div>
          <div className="text-xs text-gray-600">Per Week</div>
        </div>
        <div className="text-center p-3 bg-gray-50 rounded-lg">
          <div className="text-2xl font-bold text-red-600">{stats.backToBackMeetings}</div>
          <div className="text-xs text-gray-600">Back-to-Back</div>
        </div>
      </div>

      {/* Footer */}
      <div className="text-center text-sm text-gray-500 pt-4 border-t border-gray-200">
        Generated by Meeting Fatigue Calculator
      </div>
    </div>
  );
}

export default FatigueScoreCard;
