import { FatigueScore, MeetingStats } from '../types';

interface FatigueScoreCardProps {
  fatigueScore: FatigueScore;
  stats: MeetingStats;
}

const gradeColors = {
  A: 'from-green-500 to-green-600',
  B: 'from-blue-500 to-blue-600',
  C: 'from-yellow-500 to-yellow-600',
  D: 'from-orange-500 to-orange-600',
  F: 'from-red-500 to-red-600',
};

function FatigueScoreCard({ fatigueScore, stats }: FatigueScoreCardProps) {
  const avgWeeklyHours = ((stats.totalHours / 30) * 7).toFixed(1);

  return (
    <div className="bg-white rounded-2xl shadow-2xl p-8 max-w-2xl mx-auto border-4 border-gray-200">
      <div className="text-center mb-6">
        <h2 className="text-3xl font-bold mb-2">Meeting Fatigue Report Card</h2>
        <p className="text-gray-600">Last 30 Days Analysis</p>
      </div>

      {/* Score Circle */}
      <div className="flex justify-center mb-8">
        <div className="relative">
          <svg className="w-48 h-48 transform -rotate-90">
            <circle
              cx="96"
              cy="96"
              r="88"
              stroke="#e5e7eb"
              strokeWidth="12"
              fill="none"
            />
            <circle
              cx="96"
              cy="96"
              r="88"
              stroke="url(#gradient)"
              strokeWidth="12"
              fill="none"
              strokeDasharray={`${(fatigueScore.score / 100) * 553} 553`}
              strokeLinecap="round"
            />
            <defs>
              <linearGradient id="gradient" x1="0%" y1="0%" x2="100%" y2="100%">
                <stop offset="0%" className={`${gradeColors[fatigueScore.grade]}`} stopColor="#3b82f6" />
                <stop offset="100%" className={`${gradeColors[fatigueScore.grade]}`} stopColor="#8b5cf6" />
              </linearGradient>
            </defs>
          </svg>
          <div className="absolute inset-0 flex flex-col items-center justify-center">
            <div className={`text-6xl font-bold bg-gradient-to-r ${gradeColors[fatigueScore.grade]} bg-clip-text text-transparent`}>
              {fatigueScore.score}
            </div>
            <div className="text-2xl font-semibold text-gray-700">{fatigueScore.grade}</div>
          </div>
        </div>
      </div>

      {/* Badge */}
      <div className="text-center mb-6">
        <div className="inline-block bg-gradient-to-r from-blue-50 to-purple-50 rounded-full px-6 py-3 border-2 border-blue-200">
          <p className="text-lg font-semibold text-gray-800">{fatigueScore.badge}</p>
        </div>
      </div>

      {/* Quick Stats */}
      <div className="grid grid-cols-3 gap-4 mb-6">
        <div className="text-center p-3 bg-gray-50 rounded-lg">
          <div className="text-2xl font-bold text-blue-600">{stats.totalMeetings}</div>
          <div className="text-xs text-gray-600">Meetings</div>
        </div>
        <div className="text-center p-3 bg-gray-50 rounded-lg">
          <div className="text-2xl font-bold text-purple-600">{avgWeeklyHours}h</div>
          <div className="text-xs text-gray-600">Per Week</div>
        </div>
        <div className="text-center p-3 bg-gray-50 rounded-lg">
          <div className="text-2xl font-bold text-red-600">{stats.backToBackMeetings}</div>
          <div className="text-xs text-gray-600">Back-to-Back</div>
        </div>
      </div>

      {/* Footer */}
      <div className="text-center text-sm text-gray-500 pt-4 border-t border-gray-200">
        Generated by Meeting Fatigue Calculator
      </div>
    </div>
  );
}

export default FatigueScoreCard;
